# Generated by Django 4.2.7 on 2024-12-05 18:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoqueue',
            options={},
        ),
        migrations.AddField(
            model_name='slot',
            name='dept_loc',
            field=models.CharField(choices=[('IITJ', 'IIT Jodhpur'), ('NIFTJ', 'NIFT Jodhpur'), ('Paota', 'Paota'), ('Ratanada', 'Ratanada'), ('Sardarpura', 'Sardarpura')], default='Paota', max_length=10),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_loc',
            field=models.CharField(choices=[('IITJ', 'IIT Jodhpur'), ('NIFTJ', 'NIFT Jodhpur'), ('Paota', 'Paota'), ('Ratanada', 'Ratanada'), ('Sardarpura', 'Sardarpura')], default='IITJ', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
