# Generated by Django 4.2.7 on 2024-12-06 10:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_autoqueue_options_slot_dept_loc_slot_start_loc_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='dept_loc',
            new_name='dest_loc',
        ),
        migrations.RemoveField(
            model_name='autoqueue',
            name='position',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='creator',
        ),
        migrations.AddField(
            model_name='autoqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='autoqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='autoqueue',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slot',
            name='auto',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.auto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auto',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('QUEUED', 'Queued')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='autoqueue',
            name='auto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_queue', to='api.auto'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('PENDING_DRIVER', 'Pending Driver'), ('OPEN', 'Open'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('FINALIZED', 'Finalized')], default='PENDING_DRIVER', max_length=15),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.slot'),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
