# Generated by Django 4.2.7 on 2024-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers_rename_dept_loc_slot_dest_loc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoqueue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='autoqueue',
            name='user',
        ),
        migrations.AlterField(
            model_name='slot',
            name='current_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
