# Generated by Django 4.2.7 on 2024-12-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_autoqueue_status_remove_autoqueue_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
